## Exercise 1 - Queries and use of Pandas

- Calculate the 5 highest-priced suburbs on average in Melbourne.

- Calculate the 5 highest airbnb monthly priced suburbs on average. (you'll
have to merge the Airbnb data frame by zipcode as notebook `02__combining_datasets.ipynb`)

- Calculate the mean, median, max, min, and quartiles of grouping by property type
and SellerG.

Retrieve the number of properties in Melbourne that have less or equal than one bathroom and
which are located in a suburb with more than 2000 properties, (don't use
property count)

In [1]:
import pandas

import seaborn
seaborn.set_context('talk')
pandas.set_option("display.max_columns", None)

melb_df = pandas.read_csv('https://www.famaf.unc.edu.ar/~nocampo043/no_nan_values_melb.csv')
melb_df[:3]

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,suburb_count,CouncilArea_mode
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,2.0,1.0,1.0,202.0,137.374429,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0,56,Yarra
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,2.0,1.0,0.0,156.0,79.000000,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0,56,Yarra
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,3.0,2.0,0.0,134.0,150.000000,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0,56,Yarra

In [5]:
interesting_cols = [
  'street', 'neighborhood', 'city', 'suburb', 'state', 'zipcode',
  'price', 'weekly_price', 'monthly_price',
  'latitude', 'longitude',
]
airbnb_df = pandas.read_csv(
    'https://cs.famaf.unc.edu.ar/~mteruel/datasets/diplodatos/cleansed_listings_dec18.csv',
    usecols=interesting_cols)
airbnb_df[:3]

/tmp/ipykernel_11048/3447934477.py:6: DtypeWarning: Columns (35) have mixed types. Specify dtype option on import or set low_memory=False.
  airbnb_df = pandas.read_csv(

,street,neighborhood,city,suburb,state,zipcode,latitude,longitude,price,weekly_price,monthly_price
0,"Bulleen, VIC, Australia",Balwyn North,Manningham,Bulleen,VIC,3105,-37.772684,145.092133,60,NaN,NaN
1,"Brunswick East, VIC, Australia",Brunswick,Moreland,Brunswick East,VIC,3057,-37.766505,144.980736,35,200.0,803.0
2,"St Kilda, VIC, Australia",St Kilda,Port Phillip,St Kilda,VIC,3182,-37.859755,144.977369,159,1253.0,4452.0

## Exercise 2

- Using the reduced numerical features obtained with PCA in the practical
  exercise `01__practical_exercises.ipynb`.
- Then, apply MDS, LLE, Isomap, or TSNE.

In [13]:
categorical_vars = ['Suburb', 'Type', 'Method', 'SellerG', 'CouncilArea', 'Regionname', "Address", "CouncilArea_mode", "Date"]
numerical_vars = list(set(melb_df.columns) - set(categorical_vars))

melb_df_num = (
    (melb_df[numerical_vars] - melb_df[numerical_vars].mean(axis=0)
) / melb_df[numerical_vars].std(axis=0))

from sklearn.decomposition import PCA
pca = PCA(n_components=4)
pca.fit(melb_df_num)
proyected_features = pca.transform(melb_df_num)

In [14]:
proyected_features

array([[-1.17210699, -0.10968321, -1.50568663,  1.51382119],
       [-1.95909527, -0.14226745, -1.6531638 ,  1.45770748],
       [ 0.17180495,  0.12386468, -1.40272931,  2.30417028],
       ...,
       [ 1.06657375,  1.47484122, -0.35142585,  0.18347251],
       [ 2.91868809,  1.40729961, -0.15031701,  0.65428692],
       [ 0.43835414,  1.62920308,  0.19693808,  1.25374801]])